# Generated by Django 4.0.5 on 2022-09-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255, verbose_name='FISh')),
                ('task', models.CharField(max_length=255, verbose_name='Mavzu')),
                ('file', models.FileField(upload_to='db_files', verbose_name='Video')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
